// apps/react/src/App.tsx
import '@/styles/globals.css'
import '@iamprompt/flex-render/css'

import FlexPreview from '@iamprompt/flex-render/react'

import { FlexModules } from '@/utils/flex'

import ViewJSONButton from './components/ViewJSONButton'

function App() {
  return (
    <div className="m-8">
      {FlexModules.map(({ id, title, json, author, authorUrl }) => (
        <div data-id={id} key={id}>
          <div className="flex mt-8 mb-4 flex-col sm:flex-row sm:items-baseline">
            <div className="flex flex-row space-x-4">
              <ViewJSONButton id={id} json={json} title={title} />
              <h2 className="font-bold text-3xl text-white">{title || id}</h2>
            </div>
            {author ? (
              <span className="sm:ml-4 text-white text-sm">
                (By{' '}
                <a href={authorUrl || '#'} rel="noreferrer" target="_blank">
                  {author}
                </a>
                )
              </span>
            ) : null}
          </div>
          <FlexPreview json={json} />
        </div>
      ))}
    </div>
  )
}

export default App

// apps/vue/src/App.vue
<script setup lang="ts">
import '@iamprompt/flex-render/css'

import FlexPreview from '@iamprompt/flex-render/vue'

import { FlexModules } from './utils/flex'
</script>

<template>
  <div class="m-8">
    <div v-for="item in FlexModules" :key="item.id">
      <div class="flex mt-8 mb-4 flex-col sm:flex-row sm:items-baseline">
        <div class="flex flex-row space-x-4">
          <h2 class="font-bold text-3xl text-white">{{ item.title || item.id }}</h2>
        </div>
        <span v-if="item.author" class="sm:ml-4 text-white text-sm">
          (By
          <a :href="item.authorUrl || '#'" rel="noreferrer" target="_blank"> {{ item.author }} </a>)
        </span>
      </div>
      <FlexPreview :json="item.json" />
    </div>
  </div>
</template>
